### ISSUE TITLE
Not working for fcitx and WPS

### ISSUE THREAD

**Issue by sammlyu** [eliranwong/ChromeOSLinux#1]
Which version of WPS you are using that can work with FCITX?
I have followed your steps to install FCITX and I'm using "wps-office_11.1.0.9719_arm64.deb".

Thanks!

**Comment by eliranwong** [comment]
I can confirm that the steps work for me.  I newly installed both wps and fcitx again.  Below is a screenshot.

![Screenshot 2022-12-26 1 45 53 AM](https://user-images.githubusercontent.com/25262722/209489302-34a11fa7-d689-489b-8587-485a8f870b8c.png)

The wps installed I downloaded is "wps-office_11.1.0.11664.XA_amd64.deb"
